// Author: Bradley R. Kinnard — your code review notes, exportable

import { useState } from 'react'
import { Suggestion } from '../api/apiClient'

interface SummaryGeneratorProps {
  suggestions: Suggestion[]
  language: string
}

export default function SummaryGenerator({ suggestions, language }: SummaryGeneratorProps) {
  const [copied, setCopied] = useState(false)

  const accepted = suggestions.filter(s => s.rated && s.accepted)
  const rejected = suggestions.filter(s => s.rated && !s.accepted)
  const unreviewed = suggestions.filter(s => !s.rated)

  // only show if user has rated at least one
  const hasRated = accepted.length > 0 || rejected.length > 0
  if (!hasRated) return null

  const generateMarkdown = () => {
    const lines: string[] = []
    lines.push(`# Code Review Summary`)
    lines.push('')
    lines.push(`| | |`)
    lines.push(`|---|---|`)
    lines.push(`| **Language** | ${language} |`)
    lines.push(`| **Date** | ${new Date().toLocaleDateString()} |`)
    lines.push(`| **Accepted** | ${accepted.length} issues to address |`)
    lines.push(`| **Rejected** | ${rejected.length} false positives |`)
    lines.push(`| **Skipped** | ${unreviewed.length} not reviewed |`)
    lines.push('')

    if (accepted.length > 0) {
      lines.push(`---`)
      lines.push('')
      lines.push(`## ✅ Issues to Fix`)
      lines.push('')

      // Group by severity for better organization
      const bySeverity = groupBySeverity(accepted)

      for (const [severity, items] of bySeverity) {
        if (items.length === 0) continue
        const label = getSeverityLabel(severity)
        const emoji = getSeverityEmoji(severity)

        lines.push(`### ${emoji} ${label} (${items.length})`)
        lines.push('')

        for (const s of items) {
          lines.push(`**${s.message}**`)
          lines.push('')
          lines.push(`> Agent: \`${s.agent}\` · Confidence: ${Math.round(s.confidence * 100)}%`)
          lines.push('')
        }
      }
    }

    if (rejected.length > 0) {
      lines.push(`---`)
      lines.push('')
      lines.push(`## ❌ Rejected (False Positives)`)
      lines.push('')
      lines.push(`These suggestions were marked as not applicable:`)
      lines.push('')
      for (const s of rejected) {
        lines.push(`- ~~${s.message}~~ *(${s.agent})*`)
      }
      lines.push('')
    }

    if (unreviewed.length > 0) {
      lines.push(`---`)
      lines.push('')
      lines.push(`## ⏸️ Not Reviewed (${unreviewed.length})`)
      lines.push('')
      lines.push(`*${unreviewed.length} suggestions were not reviewed during this session.*`)
      lines.push('')
    }

    lines.push(`---`)
    lines.push('')
    lines.push(`*Generated by [Code Style Enforcer](https://github.com/moonrunnerkc/code-style-enforcer)*`)

    return lines.join('\n')
  }

  const handleCopy = async () => {
    const md = generateMarkdown()
    try {
      await navigator.clipboard.writeText(md)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // fallback for older browsers
      const ta = document.createElement('textarea')
      ta.value = md
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleDownload = () => {
    const md = generateMarkdown()
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `code-review-${new Date().toISOString().split('T')[0]}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="summary-generator">
      <div className="summary-header">
        <span className="summary-title">📋 Review Summary</span>
        <span className="summary-stats">
          {accepted.length} accepted · {rejected.length} rejected
        </span>
      </div>
      <div className="summary-actions">
        <button className="summary-btn" onClick={handleCopy}>
          {copied ? '✓ Copied!' : '📋 Copy'}
        </button>
        <button className="summary-btn" onClick={handleDownload}>
          ⬇ Download .md
        </button>
      </div>
    </div>
  )
}

function getSeverityLabel(severity: number): string {
  switch (severity) {
    case 5: return 'Critical'
    case 4: return 'Error'
    case 3: return 'Warning'
    case 2: return 'Info'
    default: return 'Hint'
  }
}

function getSeverityEmoji(severity: number): string {
  switch (severity) {
    case 5: return '🔴'
    case 4: return '🟠'
    case 3: return '🟡'
    case 2: return '🔵'
    default: return '⚪'
  }
}

function groupBySeverity(suggestions: Suggestion[]): Map<number, Suggestion[]> {
  const groups = new Map<number, Suggestion[]>()
  // Initialize in order (highest severity first)
  for (const sev of [5, 4, 3, 2, 1]) {
    groups.set(sev, [])
  }
  for (const s of suggestions) {
    const sev = Math.min(5, Math.max(1, s.severity || 2))
    groups.get(sev)?.push(s)
  }
  return groups
}
